kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java)))) mvn -f pom.xml spring-boot:run"

[services.production]

[services.production.build]
args = ["bash", "-lc", "JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java)))) mvn -f artifacts/api-server/pom.xml package -DskipTests"]

[services.production.build.env]
SPRING_PROFILES_ACTIVE = "production"

[services.production.run]
args = ["java", "-jar", "artifacts/api-server/target/ordriva-api-0.1.0.jar"]

[services.production.run.env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "production"

[services.production.health.startup]
path = "/api/healthz"
